id: fca010e28ca0492b9d401dd818959e31
initial_creation_type: ocr
source_metadata:
  volumes:
    820952eeabca41fd964276e0bbb81e3f:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: རྟེན་ཅིང་འབྲེལ་པར་འབྱུང་བའི་སྙིང་པོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1605
      volume_number: 57
